### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by The-Naveen** [The-Naveen/NITCONF#1]
Need to implement a login page with credentials username and password.
invalid login if any of the credentials doesn't match
proceed to home page if matched.
(Connection to database is not necessary as of now just the outline is fine)

**Comment by Peerikatla** [comment]
Comments are not meaningful.

**Comment by Peerikatla** [comment]
Make some changes in the styling-Login page

**Comment by Vijayalakshmi2805** [comment]
closing this issue as there are some mistakes made while commiting and merging
