### ISSUE TITLE
History Page

### ISSUE THREAD

**Issue by Peerikatla** [The-Naveen/NITCONF#15]
Lists all reviewed papers in the last 6 months(only after the deline is finished).
Each paper will have these options :
     -Pdf id and Downloads: Includes a paper pdf id, 'Abstract' and 'PDF Download' buttons.
     -Paper Title : Displays the paper's title .
     -Status: The final status of the paper (Accept/Reject).
     -Revision Status: Shows the revision round of the paper (e.g., first, second).
     -Deadline: Deadline of the paper. Once the deadline is finished it shows up in this page.

[Link to History Page Enhancement section in Requirements](../blob/main/src/Texts/Requirements.md#view-history-page)

**Comment by The-Naveen** [comment]
Add all Reviews
