### ISSUE TITLE
Reviewed page

### ISSUE THREAD

**Issue by Vijayalakshmi2805** [The-Naveen/NITCONF#18]
Lists all reviewed papers.
which contains:
Pdf id and Downloads: Includes a pdf id, 'Abstract' and 'PDF Download' buttons.
Paper Title and Edit Options: Displays the paper's title with 'Edit' and 'Display All Reviews' buttons. 
'Edit' allows modification of the most recent review. 'Display All' shows all past reviews.
Status: The final status of the paper (Accept/Reject).
Revision: Shows the revision round of the paper (e.g., first, second).
Deadline: The review deadline, after which the paper is removed from this page.

[Link to To Reviewed Page Enhancement section in Requirements](../blob/main/src/Texts/Requirements.md#reviewed-page)

**Comment by The-Naveen** [comment]
All The reviews are displaying
