### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by The-Naveen** [The-Naveen/NITCONF#2]
**Home** contains:
A **NITCONF** Text on the top left indirectly a link that can access home page 
**Reviewer profile** icon on the top right redirecting to reviewer profile consisting of his details
left of profile a **notification** symbol is present where it will popup the notifications that are sent by the PC.

Followed by three more icons in the middle :
1. **To Review**: redirects to To review page where the pdfs are displayed.
      https://github.com/The-Naveen/NITCONF/issues/4
2. **Reviewed**: redirects to Reviewed page where the submitted files before deadline will shown.
      https://github.com/The-Naveen/NITCONF/issues/18
3. **History**: redirects to History page where the successfully submitted files are held. (after submission)
      https://github.com/The-Naveen/NITCONF/issues/15

**Comment by Vijayalakshmi2805** [comment]
The paths are to be mentioned correctly for the icon and images
