### ISSUE TITLE
Reviewer profile

### ISSUE THREAD

**Issue by The-Naveen** [The-Naveen/NITCONF#3]
A **Reviewer profile** page
the top portion of the page consisting of
1. **NITCONF** redirecting to home page
      https://github.com/The-Naveen/NITCONF/issues/2
2. **To review** redirecting to to review page
      https://github.com/The-Naveen/NITCONF/issues/4
3. **reviewed** redirecting to reviewed page
      https://github.com/The-Naveen/NITCONF/issues/18
4. **history** redirecting to history page
      https://github.com/The-Naveen/NITCONF/issues/15
5. **notifications** redirecting to notification page
      https://github.com/The-Naveen/NITCONF/issues/22
* We will aslo have an option to logout 
   
and the details of the reviewer will be present in the middle 
Name, Surname etc

**Comment by Peerikatla** [comment]
Needed an enhancement, Logout option is missing..
